

services:

  db:
    container_name: postgres-17rc1-alpine3.20
    image: postgres:17rc1-alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432

  adminer:
    container_name:  "postgres-17rc1-alpine3.20-adminer"
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 8088:8080


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - 8081:80
      # Change the number before : to the port the SMTP server should be accessible on
      - 8025:25

